// playgrounds/vue/src/components/switch/SwitchWithAnimations.vue
<!-- 
  展示 Switch 组件的各种动画效果
  包括:
  1. 基础过渡动画
  2. 弹性动画
  3. 图标动画
  4. 手势动画
-->
<script setup lang="ts">
import { ref } from 'vue'
import { Switch, SwitchLabel } from '@headlessui/vue'
import { useMotion } from '@vueuse/motion'

const enabled = ref(false)
const switchThumb = ref(null)

const motionConfig = {
  initial: { x: 0, scale: 1 },
  enter: { 
    x: enabled.value ? 20 : 0,
    scale: enabled.value ? 1.1 : 1,
    transition: {
      type: 'spring',
      stiffness: 500,
      damping: 30
    }
  }
}

useMotion(switchThumb, motionConfig)

// 监听状态变化更新动画
watch(enabled, (newValue) => {
  motionConfig.enter.x = newValue ? 20 : 0
  motionConfig.enter.scale = newValue ? 1.1 : 1
})
</script>

<template>
  <div class="flex h-full w-screen items-start justify-center bg-gray-50 p-12">
    <div class="w-full max-w-md space-y-8">
      <!-- 基础动画开关 -->
      <div class="space-y-2">
        <h3 class="text-sm font-medium text-gray-900">基础动画效果</h3>
        <div class="flex items-center space-x-4">
          <SwitchLabel class="text-sm text-gray-700">
            平滑过渡效果
          </SwitchLabel>
          <Switch
            v-model="enabled"
            :class="[
              'relative inline-flex h-6 w-11 cursor-pointer rounded-full',
              'transition-colors duration-200 ease-in-out',
              'focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-2',
              enabled ? 'bg-blue-600' : 'bg-gray-200'
            ]"
          >
            <span
              ref="switchThumb"
              class="inline-block h-5 w-5 transform rounded-full bg-white"
            />
          </Switch>
        </div>
      </div>

      <!-- 弹性动画开关 -->
      <div class="space-y-2">
        <h3 class="text-sm font-medium text-gray-900">弹性动画效果</h3>
        <div class="flex items-center space-x-4">
          <SwitchLabel class="text-sm text-gray-700">
            弹性过渡效果
          </SwitchLabel>
          <Switch
            v-model="enabled"
            :class="[
              'relative inline-flex h-6 w-11 cursor-pointer rounded-full',
              'transition-colors duration-200 ease-in-out',
              'focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-2',
              enabled ? 'bg-blue-600' : 'bg-gray-200'
            ]"
          >
            <transition
              enter-active-class="transform transition ease-out duration-200"
              enter-from-class="translate-x-0 scale-95"
              enter-to-class="translate-x-5 scale-100"
              leave-active-class="transform transition ease-in duration-200"
              leave-from-class="translate-x-5 scale-100"
              leave-to-class="translate-x-0 scale-95"
            >
              <span
                class="inline-block h-5 w-5 transform rounded-full bg-white"
                :class="{ 'translate-x-5': enabled }"
              />
            </transition>
          </Switch>
        </div>
      </div>

      <!-- 图标动画开关 -->
      <div class="space-y-2">
        <h3 class="text-sm font-medium text-gray-900">图标动画效果</h3>
        <div class="flex items-center space-x-4">
          <SwitchLabel class="text-sm text-gray-700">
            图标过渡效果
          </SwitchLabel>
          <Switch
            v-model="enabled"
            :class="[
              'relative inline-flex h-8 w-14 cursor-pointer rounded-full',
              'transition-colors duration-200 ease-in-out',
              'focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-2',
              enabled ? 'bg-blue-600' : 'bg-gray-200'
            ]"
          >
            <transition
              enter-active-class="transform transition ease-out duration-200"
              enter-from-class="translate-x-0 opacity-0"
              enter-to-class="translate-x-6 opacity-100"
              leave-active-class="transform transition ease-in duration-200"
              leave-from-class="translate-x-6 opacity-100"
              leave-to-class="translate-x-0 opacity-0"
            >
              <span
                class="relative inline-block h-7 w-7 transform rounded-full bg-white"
                :class="{ 'translate-x-6': enabled }"
              >
                <svg
                  class="absolute inset-0 h-full w-full p-1"
                  fill="none"
                  viewBox="0 0 24 24"
                  :stroke="enabled ? '#2563eb' : '#9ca3af'"
                >
                  <transition
                    enter-active-class="transition-opacity duration-200 delay-100"
                    enter-from-class="opacity-0"
                    enter-to-class="opacity-100"
                    leave-active-class="transition-opacity duration-200"
                    leave-from-class="opacity-100"
                    leave-to-class="opacity-0"
                  >
                    <path
                      v-if="enabled"
                      stroke-linecap="round"
                      stroke-linejoin="round"
                      stroke-width="2"
                      d="M5 13l4 4L19 7"
                    />
                    <path
                      v-else
                      stroke-linecap="round"
                      stroke-linejoin="round"
                      stroke-width="2"
                      d="M6 18L18 6M6 6l12 12"
                    />
                  </transition>
                </svg>
              </span>
            </transition>
          </Switch>
        </div>
      </div>
    </div>
  </div>
</template>

// playgrounds/react/pages/switch/switch-with-animations.tsx
import { Switch } from '@headlessui/react'
import { useState } from 'react'
import { motion } from 'framer-motion'
import { classNames } from '../../utils/class-names'

/**
 * Switch 组件动画示例
 * 展示了如何:
 * 1. 使用 Framer Motion 添加流畅动画
 * 2. 自定义过渡效果
 * 3. 添加手势动画
 */
export default function AnimatedSwitch() {
  const [enabled, setEnabled] = useState(false)

  return (
    <div className="flex h-full w-screen items-start justify-center bg-gray-50 p-12">
      <div className="w-full max-w-md space-y-8">
        {/* 基础动画开关 */}
        <div className="space-y-2">
          <h3 className="text-sm font-medium text-gray-900">基础动画效果</h3>
          <Switch.Group>
            <div className="flex items-center space-x-4">
              <Switch.Label className="text-sm text-gray-700">
                平滑过渡效果
              </Switch.Label>
              <Switch
                checked={enabled}
                onChange={setEnabled}
                className={`
                  relative inline-flex h-6 w-11 cursor-pointer rounded-full
                  ${enabled ? 'bg-blue-600' : 'bg-gray-200'}
                  transition-colors duration-200 ease-in-out
                  focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-2
                `}
              >
                <motion.span
                  className="inline-block h-5 w-5 transform rounded-full bg-white"
                  layout
                  transition={{
                    type: "spring",
                    stiffness: 500,
                    damping: 30
                  }}
                  animate={{
                    x: enabled ? 20 : 0
                  }}
                />
              </Switch>
            </div>
          </Switch.Group>
        </div>

        {/* 弹性动画开关 */}
        <div className="space-y-2">
          <h3 className="text-sm font-medium text-gray-900">弹性动画效果</h3>
          <Switch.Group>
            <div className="flex items-center space-x-4">
              <Switch.Label className="text-sm text-gray-700">
                弹性过渡效果
              </Switch.Label>
              <Switch
                checked={enabled}
                onChange={setEnabled}
                className={`
                  relative inline-flex h-6 w-11 cursor-pointer rounded-full
                  ${enabled ? 'bg-blue-600' : 'bg-gray-200'}
                  transition-colors duration-200 ease-in-out
                  focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-2
                `}
              >
                <motion.span
                  className="inline-block h-5 w-5 transform rounded-full bg-white"
                  layout
                  transition={{
                    type: "spring",
                    stiffness: 700,
                    damping: 15
                  }}
                  animate={{
                    x: enabled ? 20 : 0,
                    scale: enabled ? 1.1 : 1
                  }}
                  whileTap={{ scale: 0.9 }}
                />
              </Switch>
            </div>
          </Switch.Group>
        </div>

        {/* 带图标动画开关 */}
        <div className="space-y-2">
          <h3 className="text-sm font-medium text-gray-900">图标动画效果</h3>
          <Switch.Group>
            <div className="flex items-center space-x-4">
              <Switch.Label className="text-sm text-gray-700">
                图标过渡效果
              </Switch.Label>
              <Switch
                checked={enabled}
                onChange={setEnabled}
                className={`
                  relative inline-flex h-8 w-14 cursor-pointer rounded-full
                  ${enabled ? 'bg-blue-600' : 'bg-gray-200'}
                  transition-colors duration-200 ease-in-out
                  focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-2
                `}
              >
                <motion.span
                  className="relative inline-block h-7 w-7 transform rounded-full bg-white"
                  layout
                  transition={{
                    type: "spring",
                    stiffness: 500,
                    damping: 30
                  }}
                  animate={{
                    x: enabled ? 24 : 0
                  }}
                >
                  <motion.svg
                    className="absolute inset-0 h-full w-full p-1"
                    fill="none"
                    viewBox="0 0 24 24"
                    stroke={enabled ? '#2563eb' : '#9ca3af'}
                    initial={false}
                    animate={{
                      pathLength: 1,
                      opacity: 1
                    }}
                  >
                    {enabled ? (
                      <motion.path
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        strokeWidth={2}
                        d="M5 13l4 4L19 7"
                        initial={{ pathLength: 0, opacity: 0 }}
                        animate={{ pathLength: 1, opacity: 1 }}
                        transition={{ duration: 0.2, delay: 0.1 }}
                      />
                    ) : (
                      <motion.path
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        strokeWidth={2}
                        d="M6 18L18 6M6 6l12 12"
                        initial={{ pathLength: 0, opacity: 0 }}
                        animate={{ pathLength: 1, opacity: 1 }}
                        transition={{ duration: 0.2, delay: 0.1 }}
                      />
                    )}
                  </motion.svg>
                </motion.span>
              </Switch>
            </div>
          </Switch.Group>
        </div>

        {/* 手势动画开关 */}
        <div className="space-y-2">
          <h3 className="text-sm font-medium text-gray-900">手势动画效果</h3>
          <Switch.Group>
            <div className="flex items-center space-x-4">
              <Switch.Label className="text-sm text-gray-700">
                拖拽切换效果
              </Switch.Label>
              <Switch
                checked={enabled}
                onChange={setEnabled}
                className={`
                  relative inline-flex h-8 w-14 cursor-pointer rounded-full
                  ${enabled ? 'bg-blue-600' : 'bg-gray-200'}
                  transition-colors duration-200 ease-in-out
                  focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-2
                `}
              >
                <motion.span
                  className="inline-block h-7 w-7 transform rounded-full bg-white shadow-lg"
                  drag="x"
                  dragConstraints={{
                    left: 0,
                    right: 24
                  }}
                  dragElastic={0.1}
                  dragMomentum={false}
                  onDragEnd={(_, info) => {
                    if (Math.abs(info.offset.x) > 10) {
                      setEnabled(!enabled)
                    }
                  }}
                  animate={{
                    x: enabled ? 24 : 0
                  }}
                  transition={{
                    type: "spring",
                    stiffness: 500,
                    damping: 30
                  }}
                  whileTap={{ scale: 0.95 }}
                  whileHover={{ scale: 1.05 }}
                />
              </Switch>
            </div>
          </Switch.Group>
        </div>
      </div>
    </div>
  )
}
